[versions]
activityCompose = "1.12.3"
android-gradlePlugin = "9.0.0"
androidCompileSdk = "36"
androidMinSdk = "24"
androidWearMinSdk = "25"
google-ksp = "2.3.5"
jetbrains-compose = "1.10.0"
jetbrains-composeMaterial3 = "1.9.0"
jetbrains-composeMaterialIconsExtended = "1.7.3"
jetbrains-dokka = "2.1.0"
jetbrains-navigation = "2.9.1"
kotlin = "2.3.0"
kotlinpoet = "2.2.0"
ktlint = "1.8.0"
navigationComposeExtended = "1.6.0"
spotless = "8.2.1"
vanniktechMavenPublishPlugin = "0.33.0"
wearCompose = "1.5.6"

[libraries]
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "android-gradlePlugin" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-wearCompose-navigation = { module = "androidx.wear.compose:compose-navigation", version.ref = "wearCompose" }

jetbrains-androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "jetbrains-navigation" }
jetbrains-compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "jetbrains-compose" }
jetbrains-compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "jetbrains-composeMaterial3" }
jetbrains-compose-materialIconsExtended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "jetbrains-composeMaterialIconsExtended" }
jetbrains-compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "jetbrains-compose" }
jetbrains-compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "jetbrains-compose" }

kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

google-ksp-symbolProcessingApi = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "google-ksp" }

spotless-gradlePlugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }

squareup-kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
squareup-kotlinpoetKsp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinpoet" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradlePlugin" }
android-kotlinMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "android-gradlePlugin" }
android-library = { id = "com.android.library", version.ref = "android-gradlePlugin" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "google-ksp" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "jetbrains-compose" }
jetbrains-dokka = { id = "org.jetbrains.dokka", version.ref = "jetbrains-dokka" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
vanniktechMavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktechMavenPublishPlugin" }
